# We need to tell RuboCop where to find our custom Cop.
# (Normally we would omit the step1 directory.)
require: ./lib/rubocop/cop/style/step1/haiku_comments.rb

AllCops:
  Exclude:
    - ./lib/**/*
  NewCops: enable
  UseCache: false

